### ISSUE TITLE
Comparing two chipertext in CKKS 

### ISSUE THREAD

**Issue by giammarcoromagnoli** [morfix-io/node-seal#102]
Hello,

I am using CKKS and I would like to compare two chipertext to see if the first one is greater than a certain threshold.
I have integer values as a message.

For example, I have Enc(832) and I would check if it is greater than Enc(850).

How could I accomplish this?

Thank you.

**Comment by s0l0ist** [comment]
Hey @giammarcoromagnoli, this question is better asked on https://github.com/microsoft/SEAL's page.
