### ISSUE TITLE
PlainText seem not working

### ISSUE THREAD

**Issue by bbzam** [morfix-io/node-seal#120]
Hi,

  I have tried using both plaintext.load (commented below) and encoder.encode to construct a PlainText object that I would be using for encryption. However, it seems that the code isnt executing as when I do a console.log("here2") after said lines, it doesn't go there. Please advise... Btw, init() is used by my other function generateKey (which generates both public and privatekey) and it works fine.

Thanks,
Benjie

```
async function encrypt(file, keyfromDB) {
  await init();
  
  //encode plaintext to be encrypted
  let buff = fs.readFileSync("uploads/" + file);
  const plaintext = seal.PlainText();

  /* let base64data = buff.toString('base64');
  console.log(base64data);
  plaintext.load(context, base64data);
  console.log("here2");*/

  const encoder = seal.BatchEncoder(context);
  const uint32array = new Uint32Array(buff);
  console.log(uint32array);
  plaintext = encoder.encode(uint32array);
  console.log("here2");`
```

**Comment by bbzam** [comment]
Thanks @s0l0ist. Please see below my init function (contains my encryption parameters). The plaintext is from a buffer which I read from a file:

async function encrypt(file, keyfromDB) {
await init();

//encode plaintext to be encrypted
let buff = fs.readFileSync("uploads/" + file);
const plaintext = seal.PlainText();

const encoder = seal.BatchEncoder(context);
const uint32array = new Uint32Array(buff);
console.log(uint32array);
plaintext = encoder.encode(uint32array);
console.log("here2");
....
}

```
async function init() {
    seal = await SEAL()
    const schemeType = seal.SchemeType.bfv
    const securityLevel = seal.SecurityLevel.tc128
    const polyModulusDegree = 4096
    const bitSizes = [36, 36, 37]
    const bitSize = 20

    const parms = seal.EncryptionParameters(schemeType)

    // Set the PolyModulusDegree
    parms.setPolyModulusDegree(polyModulusDegree)

    // Create a suitable set of CoeffModulus primes
    parms.setCoeffModulus(
        seal.CoeffModulus.Create(polyModulusDegree, Int32Array.from(bitSizes))
    )

    // Set the PlainModulus to a prime of bitSize 20.
    parms.setPlainModulus(
        seal.PlainModulus.Batching(polyModulusDegree, bitSize)
    )

    context = seal.Context(
        parms, // Encryption Parameters
        true, // ExpandModChain
        securityLevel // Enforce a security level
    );  

    if (!context.parametersSet()) {
        throw new Error(
            'Could not set the parameters in the given context. Please try different encryption parameters.'
        )
    }
    console.log("init done");
}
```

**Comment by s0l0ist** [comment]
Ah you're creating a `const` plaintext:

```javascript
const plaintext = seal.PlainText();
```

But later, there's an attempt to write to it:
```javascript
plaintext = encoder.encode(uint32array);
```

Instead, try passing in the `plaintext` into the encode function as the second parameter which writes to the underlying WASM instance inside the `const` object:
```javascript
encoder.encode(uint32array, plainText);
```

**Comment by bbzam** [comment]
Thanks @s0l0ist. Ive tried both suggestions - doing the 2nd parameter (screenshot below) and just commenting our the const plaintext line. However, my code seems not to go through, i.e. the **console.log("here2")** is not executed

![image](https://user-images.githubusercontent.com/33444249/147638715-c0f54057-e58e-4c33-a1e1-cfb8ce357d0a.png)

**Comment by s0l0ist** [comment]
In your screenshot, you're still assigning the return value (which is now null) to the const plaintext.

Don't assign anything if you're going to pass in the plaintext as the second parameter.

**Comment by bbzam** [comment]
Hi @s0l0ist, tried doing that and even removed the const line (screenschot #1)  but still no cigar:
![image](https://user-images.githubusercontent.com/33444249/147845904-0b6645bd-97f5-471f-8fe8-e85b0740893c.png)

Next, tried your original suggestion of doing `const plaintext = encoder.encode(uint32array);` but still code doesn't go to the console.log("here2") line

**Comment by NuitNoire7** [comment]
Hi @s0l0ist,

I am working under @bbzam, we've tried the code for encryption and it seems to be working on smaller files but I am getting an error while trying to encrypt larger files. I attached here the screenshots I have taken while encrypting the JSON files with 1KB and 830 KB in size. I would like to ask if you have already encountered this problem and if you could kindly suggest any solution we can try. 

![image](https://user-images.githubusercontent.com/97526582/148949199-b73d2f1f-8f84-4c18-ad0a-28b318b2684a.png)
![image](https://user-images.githubusercontent.com/97526582/148949269-1701d1b1-4511-4de3-9a55-dc6ca2197293.png)
![image](https://user-images.githubusercontent.com/97526582/148949357-4cc3f90d-7ddb-4f0e-8a8c-53c795b67287.png)
![image](https://user-images.githubusercontent.com/97526582/148949392-ec694722-4aa4-40a6-949c-0a5b7fefdd0f.png)
![image](https://user-images.githubusercontent.com/97526582/148950077-12ed1f4a-1da2-4258-8c05-7edaa18a6dfd.png)
![image](https://user-images.githubusercontent.com/97526582/148950224-52d94fbf-c221-4c1c-a081-d27b6136af09.png)
![image](https://user-images.githubusercontent.com/97526582/148950498-451a40f2-db37-407f-9cf1-9c62d92adc52.png)

Thanks,
Krizzel

**Comment by s0l0ist** [comment]
Ah I see the problem, you're attempting to encode an array of elements (Uint32) that is larger than the encryption parameters support.

The limit for the number of items you can encode/decode is equal to the Polymodulus Degree. In your case, that is `4096`. You cannot encode more elements than that limit unfortunately.
