### ISSUE TITLE
encrypted1 is not valid for encryption parameters

### ISSUE THREAD

**Issue by nikita-fuchs** [morfix-io/node-seal#121]
I'm trying to play around with the hosted sandbox, but no matter what I do, I always get the error `encrypted1 is not valid for encryption parameters`. Before running anything, I generated all the necessary parts. Maybe I am doing something wrong - is there some guide how to use the [sandbox](https://morfix.io/sandbox)?

**Comment by s0l0ist** [comment]
Can you post a screenshot with the params that you've set?

**Comment by nikita-fuchs** [comment]
I left all input values unchanged and tried adding two ciphers:
![morfix io_sandbox](https://user-images.githubusercontent.com/11761828/153158477-15447547-5c38-4e7d-8853-8cc9ce1a1e30.png)

**Comment by s0l0ist** [comment]
Ah so you need to encode data to a plaintext first, encrypt a plaintext to a ciphertext, <perform HE operations>, then decrypt to a plaintext, and finally decode the plaintext to get the results.
