### ISSUE TITLE
how can i use SEAL instance in different environment

### ISSUE THREAD

**Issue by eakeakarat** [morfix-io/node-seal#123]
I want to use an instance like context, publicKey, secretKey and etc. with another device that has own SEAL. but when I export instance to another device and use it with SEAL in each device it not work

have a specific method to share instance like context to other device or other environment that instance still work with other environment ?

this diagram would help to explain this system.
![Untitled Diagram drawio](https://user-images.githubusercontent.com/26356343/155533229-52852b8f-b7e3-4298-8062-757c1d4a1f56.png)

description:
device1: config context, publicKey, secretKey
device2: use context and publicKey from device1 to create Encryptor and encrypt plainText to cipherText
device3: use context from device1 with Evaluator to process with cipherText
device4: use context and secretKey from device1 with Decrypter cipherText to plainText
ps. all device use own SEAL ==> [from require ('node-seal')]

**Comment by s0l0ist** [comment]
You shouldn't and cannot pass a context to different devices. They're not indented to be used in that way and is why there aren't any serialization methods on it. Each device needs to create a new context. To achieve the same behavior you create a context using the same encryption parameters. 

You should use a shared set of encryption parameters by creating them in the root controller (1), serializing it using .save(), and send to the other devices. Each device (2, 3, 4) would deserialize the encryption parameters and create a new context from the parameters.

Similarly, you can create keys in (1), serialize them to send over a network, then deserialize on the receiving end (2, 4) to load them in your encryptor/decryptor.

In (2), you deserialize both encryption params and public key. Create the new context from the  parms and create the encryptor using the context and public key. 

In (3), you deserialize the encryption params. Create the new context from the parms and create the evaluator using the context. 

In (4), you deserialize both encryption params and private key. Create the new context from the  parms and create the decryptor using the context and private key.
