### ISSUE TITLE
Symmetric Key (private key encryption) rather than Assymetric

### ISSUE THREAD

**Issue by amlwwalker** [morfix-io/node-seal#136]
Can I generate a single secret (symmetric key encryption) rather than assymetric key encryption (public/private) using node-seal? I understand HE supports this but not sure if node-seal does?

**Comment by s0l0ist** [comment]
Yes, you can do so using the alternate encryption methods of an Encryptor instance as stated in the [docs](https://docs.morfix.io/Encryptor.html).
