### ISSUE TITLE
Saving context when creating multiple private keys. 

### ISSUE THREAD

**Issue by iHaroon29** [morfix-io/node-seal#139]
Hello, I'm not sure if this is the right place to ask this but I've been using your package for a small university project where i'm generating individual private keys for new users who are joining our system. For some unknown reason i'm generating the same private key but the public key does vary. Is there something that i'm missing? Would really appreciate your help. Thanks

**Comment by s0l0ist** [comment]
@iHaroon29 to better answer your question, could you provide me a little context in what you're trying to do?

Generating a public key from a previously generated private key (loaded from a serialized base64 key into a KeyGenerator) will always be unique; however, they function in the same way as any other public key.

**Comment by iHaroon29** [comment]
@s0l0ist Hey, thanks for replying. So here's what i was trying to achieve, We are currently building a multi user system where each user will have a pair of private and public key. By trail and error I was able to figure out that KeyGenerator and Context were needed and more specifically it was the context that needs to be the different if I were to have different key. Is there any way i can save "context" and load it upon request? Thanks in advance.

**Comment by s0l0ist** [comment]
@iHaroon29 There's no way to save a context as the library requires a new context to be initialized and used throughout many of the constructors (both Encoders, Encryptor, Decryptor, Evaluator, KeyGenerator, etc.)

If your goal is to create multiple public keys from the same private key (public, relin,and galois are all public keys), you can pass in a privateKey instance to the constructor for the KeyGenerator.
