### ISSUE TITLE
Is anyone using any KMS to store LWE keys?

### ISSUE THREAD

**Issue by alyai-ssvinoth22** [morfix-io/node-seal#141]
Currently, I don't see any KMS support LWE Keys. How does it currently manage to store and retrieve keys? 
- Store and retrieve from AWS S3
- Store in Secret manager (but has limitation in size)
- may be vaulted as secrets.

Is there any other better way to handle key management? including Rotations?

**Comment by s0l0ist** [comment]
@alyai-ssvinoth22 node-seal is a vanilla cryptographic library. You'd have to integrate any AWS logic or any backing storage logic separately.

You can achieve that goal by using the serialized methods on ciphers, plain texts, and keys. If you want to customize the encoder you have the option to get a serialized byte array  but keep in mind you'd have to undo transformations for deserialization.
