### ISSUE TITLE
load() in public-key.js

### ISSUE THREAD

**Issue by miaaaahmed97** [morfix-io/node-seal#42]
Hey. I'm trying to load a previously saved public key (created using `keyGenerator.getPublicKey()` ) from a .csr file. I'm using the `load(context, encoded)` function from the public-key.js, but i am running into trouble.

When using the associated `save()` method, i just used it as `publicKey.save()` on my previously defined public key. But what exactly do i call the load method on ? I tried using the documentation to solve my dilemma but i'm still stuck. Any guidance would be appreciated.

**Comment by s0l0ist** [comment]
Hello @miaaaahmed97,

When you create a KeyGenerator instance with only a context parameter, it will automatically create a secret/public key pair internally. So if you call `KeyGenerator.getPublicKey()`, you will receive a JS PublicKey instance containing the key. 

From there, if you call `publicKey.save()` it will return a base64 string representation of the web assembly (C++) publicKey. In order to load a JS PublicKey, you would first create an empty JS instance and then subsequently call it’s instance method `load` and pass in a context and encoded string:

```
const publicKey = KeyGenerator.getPublicKey()
const pkeyBase64 = publicKey.save()

// ... save to a file

// create an empty JS instance of a Public jet
const newPublicKey = Morfix.PublicKey()
newPublicKey.load({
  context: myContext,
  encoded: pkeyBase64
})
```

There is a test located [here](https://github.com/morfix-io/node-seal/blob/master/src/test/keypair/keypair-scheme_BFV-poly_4096-sec_128.test.js). Others in the parent directory are similar.

Please let me know if you’re still unsuccessful.

**Comment by miaaaahmed97** [comment]
I got this error:

`BindingError: Cannot pass non-string to std::string
    at BindingError.<anonymous> (D:\Google Drive\node-seal\node_modules\node-seal\dist\seal.node.js:1:728918)
    at new BindingError (eval at aI (D:\Google Drive\node-seal\node_modules\node-seal\dist\seal.node.js:1:728716), <anonymous>:4:34)
    at KI (D:\Google Drive\node-seal\node_modules\node-seal\dist\seal.node.js:1:729216)
    at Object.toWireType (D:\Google Drive\node-seal\node_modules\node-seal\dist\seal.node.js:1:751181)
    at PublicKey$loadFromString [as loadFromString] (eval at vI (D:\Google Drive\node-seal\node_modules\node-seal\dist\seal.node.js:1:734826), <anonymous>:10:26)
    at Object.load (D:\Google Drive\node-seal\node_modules\node-seal\dist\seal.node.js:1:776843)
    at D:\Google Drive\node-seal\encrypt.js:69:23 {
  name: 'BindingError',
  message: 'Cannot pass non-string to std::string',
  stack: 'BindingError: Cannot pass non-string to std::string\n' +
    '    at BindingError.<anonymous> (D:\\Google Drive\\node-seal\\node_modules\\node-seal\\dist\\seal.node.js:1:728918)\n' +
    '    at new BindingError (eval at aI (D:\\Google Drive\\node-seal\\node_modules\\node-seal\\dist\\seal.node.js:1:728716), <anonymous>:4:34)\n' +
    '    at KI (D:\\Google Drive\\node-seal\\node_modules\\node-seal\\dist\\seal.node.js:1:729216)\n' +
    '    at Object.toWireType (D:\\Google Drive\\node-seal\\node_modules\\node-seal\\dist\\seal.node.js:1:751181)\n' +
    '    at PublicKey$loadFromString [as loadFromString] (eval at vI (D:\\Google Drive\\node-seal\\node_modules\\node-seal\\dist\\seal.node.js:1:734826), <anonymous>:10:26)\n' +
    '    at Object.load (D:\\Google Drive\\node-seal\\node_modules\\node-seal\\dist\\seal.node.js:1:776843)\n' +
    '    at D:\\Google Drive\\node-seal\\encrypt.js:69:23'
}`

**Comment by miaaaahmed97** [comment]
```
const fs = require('fs');

encyptor = function(choice){

    (async() => {
        const encodedPublicKey = await readPublicKey();
        console.log("key3", encodedPublicKey);

        (async () => {
            // ES6 or CommonJS
            // import { Seal } from 'node-seal'
            // const { Seal } = require('node-seal')
        
            // Using CommonJS for RunKit
            const { Seal } = require('node-seal')
        
            const Morfix = await Seal
        
            const parms = Morfix.EncryptionParameters({
            schemeType: Morfix.SchemeType.BFV
            })
        
            parms.setPolyModulusDegree({
            polyModulusDegree: 4096
            })
        
            // Create a suitable vector of CoeffModulus primes
            parms.setCoeffModulus({
            coeffModulus: Morfix.CoeffModulus.Create({
                polyModulusDegree: 4096,
                bitSizes: Morfix.Vector({array: new Int32Array([36,36,37]) }),
                securityLevel: Morfix.SecurityLevel.tc128
            })
            })
        
            // Set the PlainModulus to a prime of bitSize 20.
            parms.setPlainModulus({
            plainModulus: Morfix.PlainModulus.Batching({
                polyModulusDegree: 4096,
                bitSize: 20
            })
            })
        
            
            /*We are ready to construct a SEALContext
            object. This is a heavy class that checks the validity and properties of the
            parameters we just set.*/
            
            const context = Morfix.Context({
            encryptionParams: parms,
            expandModChain: true,
            securityLevel: Morfix.SecurityLevel.tc128
            })
        
            if (!context.parametersSet) {
            throw new Error('Could not set the parameters in the given context. Please try different encryption parameters.')
            }

            const publicKey = Morfix.PublicKey()
            publicKey.load({
                context: context,
                encoded: encodedPublicKey
            })

        })()
    })() 
    
}

function readPublicKey(){
    var key;
    fs.readFile('/Google Drive/node-seal/public.csr', function (err, data) {
        if (err) throw err;
        key = data;
      });
      return key;
}
```

**Comment by s0l0ist** [comment]
I think you may need to put a `return` in front of `fs.readFile ...` which would return the callback result because you’re using `await` syntax. 

In addition, you should specify an encoding option ‘utf8’ to the readFile method so that it returns a string rather than a buffer object.

In short, ensure the function you’re using to read the file is returning a string.

**Comment by miaaaahmed97** [comment]
Turns out there were a lot of problems with `readPublicKey()`. Your advice helped. Thank you.
