### ISSUE TITLE
Access Public key and Secret Key

### ISSUE THREAD

**Issue by AmitKawad** [morfix-io/node-seal#64]
Is it possible to store the Public key and secret key in a vault. I cant do that as it is returning a complete object as below

secret key  {
  instance: [Getter],
  inject: [Function: inject],
  delete: [Function: delete],
  save: [Function: save],
  saveArray: [Function: saveArray],
  load: [Function: load],
  loadArray: [Function: loadArray],
  copy: [Function: copy],
  clone: [Function: clone],
  move: [Function: move]
}

**Comment by s0l0ist** [comment]
@AmitKawad there are two methods for serializing the key, `save` and `saveArray`. `save` returns a base64 encoded string representing the secret key and can later be deserialized by creating a new secret key instance and calling the corresponding `load` instance function. `saveArray` returns a Uint8Array containing binary data.

I think your choices here would be to generate a secret key using the KeyGenerator, serialize and store the base64 encoded key into whatever vault you want, then take from the vault and deserialize when needed.
