### ISSUE TITLE
CipherText.save() generating different values

### ISSUE THREAD

**Issue by AmitKawad** [morfix-io/node-seal#65]
![Screenshot from 2020-04-23 17-00-32](https://user-images.githubusercontent.com/37235516/80094656-42232c00-8584-11ea-8049-8d8875878c6d.png)
When trying to run add two numbers twice with same public key and private key, I am getting different strings when computing cipherText.saev() as shown below.

  evaluator.add(cipherText, cipherText1, cipherText)
   console.log('cipherText----->',cipherText.save())

**Comment by s0l0ist** [comment]
@AmitKawad Could you please paste the exact example where you're experiencing this problem?

**Comment by AmitKawad** [comment]
@s0l0ist  I have generated the public key and secret key and saved them in a  file. When I want to perform any computation I read these keys from the file and do the following 

     //values[0] is the public key read from the file and values[1] is the secret key read from the file
     
      newPublicKey = values[0]
      newPrivateKey = values[1] 


      newPublicKey = Morfix.PublicKey()
      newPublicKey.load(context, values[0])

      newPrivateKey = Morfix.SecretKey()
      newPrivateKey.load(context, values[1])

      const encoder = Morfix.BatchEncoder(context)
      
      const encryptor = Morfix.Encryptor(context, newPublicKey)
      const decryptor = Morfix.Decryptor(context, newPrivateKey)
      const evaluator = Morfix.Evaluator(context)
     
      const array = Int32Array.from([1])
      const array2 = Int32Array.from([10])


      // Encode the Array
      const plainText = encoder.encode(array)
      const plainText1 = encoder.encode(array2)
      
      // Encrypt the PlainText

      const cipherText = encryptor.encrypt(plainText)
      const cipherText1 = encryptor.encrypt(plainText1)

      console.log('cipher----------------------------\n')
      console.log("cipherText --> \n", cipherText.save())



On the last line in the above code snippet, every time I run my code I get different values for cipherText.save() , however everytime I am using same  two arrays for performing addition and reading same keys from the file 


evaluator.add(cipherText, cipherText1, cipherText)  // Op (A), Op (B), Op (Dest)
 console.log('CipherText after add', cipherText.save())

Also the cipherText after performing addition on the above line is different everytime I run the code with same 2 arrays and same keys from the file.

I am expecting the ciphers to be the same everytime,  provided that the arrays are same and keys used are same everytime.

**Comment by s0l0ist** [comment]
Thank you for the example.

This is due to probabilistic properties of the library. Meaning there’s a random factor introduced in every encryption of a plaintext (IND-CPA):

```
Semantic Security or IND-CPA Security: At a high level, a homomorphic encryption scheme is said to be secure if no adversary has an advantage in guessing (with better than 50% chance) whether a given ciphertext is an encryption of either one of two equally likely distinct messages. This requires encryption to be randomized so that two different encryptions of the same message do not look the same.
```

So in your case, this is the expected behavior. 
The resultant Ciphertext should still decrypt to the desired output.
