### ISSUE TITLE
RangeError: WebAssemblyMemory()

### ISSUE THREAD

**Issue by AmitKawad** [morfix-io/node-seal#68]
When I am trying to test the load on my application which hits the service number of times, I get the following error 
RangeError: WebAssemblyMemory(): could not allocate memory. 
Is there any way I can fix this memory allocation ?

**Comment by s0l0ist** [comment]
There could be two problems you’re experiencing:
1. Memory leaks: objects garbage collected by JS, but are still occupying memory in WASM
2. You’re generating large encryption parameters such as polyModulusDegree of 16384 and generating/serializing Galois keys

Most likely you’re experiencing the first problem. From the readme - Unfortunately, the typical way of cleaning up dereferenced JS objects will leave behind a the Web Assembly (C++) object in memory. There is no way to automatically call the destructors on C++ objects. JavaScript code must explicitly delete any C++ object handles it has received, or the heap will grow indefinitely.

<instance>.delete()

You can also checkout the benchmark scripts to see a better example of how to properly GC.
