### ISSUE TITLE
polymodulus, bitsize, bitsizes

### ISSUE THREAD

**Issue by AmitKawad** [morfix-io/node-seal#69]
I am using the security level SecurityLevel.tc128 and want to use polyModulusDegree=1024 
what combinations of bitSizes [-,-,-] can i have and what should be the bitsize?

**Comment by s0l0ist** [comment]
This is a very low polyModDegree, as such you will not be able to have more than 1 bit size specified for the coeffModulus. 

If you’re using BFV scheme, you could use The `seal.CoeffModulus.BFVDefault` function To generate these value(s). 

You can also use morfix.io/sandbox to also rapidly test different parameters.
