### ISSUE TITLE
Seal header is invalid 

### ISSUE THREAD

**Issue by AmitKawad** [morfix-io/node-seal#71]
I have been using the library to build an application and everything seemed to be working fine, until I encountered an error as  **Error:loaded SEALHeader is invalid**. Are any recent changes commited to the library causing this? 
Getting the above error when I am doing the following 
cipherText.load(context,encryptedSum)  //cipherText is an instance of Morfix.CipherText()

**Comment by s0l0ist** [comment]
Yes, there's been a change to seal v3.5.1. The previous version of seal was v3.4.5 (node-seal v4.2.4)

According to their docs, it shouldn't be a breaking change between serialized SEAL Headers. Loaded objects should interpret the old header and update it to the newer version.

Do you happen to have the stored `encryptedSum` that you could share that is causing this issue?

**Comment by AmitKawad** [comment]
Yes, I have differet layers of application where one layer is responsible for computation while the other layer performs decryption, the layer that performs decryption gets the encrypted computed cipher from the first layer. I am creating a context on the second decrypting layer as well to perform decryption.

I am using the the decrption parameters as below.
      const securityLevel = Morfix.SecurityLevel.tc128
      const polyModulusDegree = 4096
      const bitSizes = [36,36,37]
      const bitSize = 20
 
     parms.setPolyModulusDegree(polyModulusDegree)
     parms.setCoeffModulus(
         Morfix.CoeffModulus.Create(polyModulusDegree, Int32Array.from(bitSizes))
     )
     parms.setPlainModulus(           
         Morfix.PlainModulus.Batching(polyModulusDegree, bitSize)
     ) 


I am using the same above context on all the layers of application wherever required.

**Comment by s0l0ist** [comment]
Your setup sounds fine. Could you provide an example serialized cipher that is failing?

**Comment by AmitKawad** [comment]
I am now able to decrypt, but when I do performance test by hitting the application to compute addition, earlier I was able to hit my application for 8379 times in 15 mins. However now my appliation crashes after hitting the service  1207 times in about 2 mins. 
I get the below error 

RuntimeError: function signature mismatch
    at wasm-function[255]:64
    at wasm-function[522]:14
    at wasm-function[134]:574
    at wasm-function[426]:243
    at wasm-function[427]:217
    at wasm-function[919]:232
    at wasm-function[229]:209
    at wasm-function[1248]:11
    at I.dynCall_viiii (/home/amit/Documents/test/node_modules/node-seal/dist/node/wasm/index.js:1:839076)
    at dynCall_viiii_405 (eval at _I (/home/amit/Documents/test/node_modules/node-seal/dist/node/wasm/index.js:1:809717), <anonymous>:4:12)
RuntimeError: function signature mismatch
    at wasm-function[255]:64
    at wasm-function[522]:14
    at wasm-function[134]:574
    at wasm-function[426]:243
    at wasm-function[427]:217
    at wasm-function[919]:232
    at wasm-function[229]:209
    at wasm-function[1248]:11
    at I.dynCall_viiii (/home/amit/Documents/test/node_modules/node-seal/dist/node/wasm/index.js:1:839076)
    at dynCall_viiii_405 (eval at _I (/home/amit/Documents/test/node_modules/node-seal/dist/node/wasm/index.js :1:809717), <anonymous>:4:12)

/home/amit/Documents/test/node_modules/node-seal/dist/node/wasm/index.js:1
(function (exports, require, module, __filename, __dirname) { !function(A,I){if("object"==typeof exports&&"object"==typeof module)module.exports=I();else if("function"==typeof define&&define.amd)define([],I);else{var g=I();for(var C in g)("object"==typeof exports?exports:A)[C]=g[C]}}("undefined"!=typeof self?self:this,(function(){return function(A){var I={};function g(C){if(I[C])return I[C].exports;var Q=I[C]={i:C,l:!1,exports:{}};return A[C].call(Q.exports,Q,Q.exports,g),Q.l=!0,Q.exports}return g.m=A,g.c=I,g.d=function(A,I,C){g.o(A,I)||Object.defineProperty(A,I,{enumerable:!0,get:C})},g.r=function(A){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(A,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(A,"__esModule",{value:!0})},g.t=function(A,I){if(1&I&&(A=g(A)),8&I)return A;if(4&I&&"object"==typeof A&&A&&A.__esModule)return A;var C=Object.create(null);if(g.r(C),Object.de

RuntimeError: abort(RuntimeError: function signature mismatch). Build with -s ASSERTIONS=1 for more info.
    at process.oA (/home/amit/Documents/test/node_modules/node-seal/dist/node/wasm/index.js:1:6649)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:94:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by s0l0ist** [comment]
Please paste the loop you’re using to benchmark. This looks to be a memory leak.

**Comment by AmitKawad** [comment]
I haven't used a benchmark script. I am using express and testing using Jmeter to hit the application.

**Comment by s0l0ist** [comment]
In that case, if you could provide the express handler logic that is causing the crash I could take a look. Otherwise I have nothing to go off of.

**Comment by AmitKawad** [comment]
@s0l0ist  Thank you for pointing out the memory leak. Able to fix it now. Could you please explain how  securityLevel.none affect and what does it do ?

**Comment by s0l0ist** [comment]
@AmitKawad Unless you are using really advanced encryption parameters for a really advanced use case, you will probably never need to set this to `none`. 

You can read a little more in the [SEAL source](https://github.com/microsoft/SEAL/blob/69fe2f4d639196556ef926d9eaaef0bf30172c42/native/src/seal/modulus.h#L383)
