### ISSUE TITLE
How can i call "CipherText.setScale"

### ISSUE THREAD

**Issue by Jongsic** [morfix-io/node-seal#81]
I need to change scale of CipherText

And CipherText.scale of `node-seal` is read-only property.

But MS-SEAL has setScale Function.

I wonder if you could help me by support CipherText.setScale in this great library?

Thank you!

**Comment by s0l0ist** [comment]
@Jongsic Thank you for your suggestion. This feature will be added in the next release over the next day or two.

**Comment by s0l0ist** [comment]
@Jongsic, a new release has been published.

**Comment by Jongsic** [comment]
Thank you for your fast and perfect supports!
