### ISSUE TITLE
Parameters for multiplication operations for polyModulusDegree = 1024   

### ISSUE THREAD

**Issue by nk307** [morfix-io/node-seal#88]
Hi, I am new in using SEAL, when i use   following parameters
const polyModulusDegree = 4096
const bitSizes = [36,36,37]
const bitSize = 20, the response output size is around 180kb,
I need an output less than or equal to 128 kb, is there any way to compress the encrypted result?

**Comment by s0l0ist** [comment]
Hello, the library has compression enabled by default so the data you see is compressed internally.

You could try to obtain binary data directly using the .saveArray() functions and using a 3rd party compression library, but this may not yield substantial savings.
